# Generated by Django 4.0.2 on 2022-02-06 00:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Palabras',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=50)),
                ('allowed', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('D', 'Deleted')], default='A', max_length=1)),
                ('dateCreated', models.DateField(auto_now_add=True)),
                ('lastUpdate', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
