# Generated by Django 4.0.2 on 2022-02-06 01:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Palabras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='palabras',
            name='dateDeleted',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
