# Generated by Django 4.0.2 on 2022-02-06 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Palabras', '0002_palabras_datedeleted'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Palabras',
            new_name='Palabra',
        ),
    ]
