# Generated by Django 4.0.2 on 2022-02-06 02:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Palabras', '0003_rename_palabras_palabra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palabra',
            name='dateCreated',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='palabra',
            name='dateDeleted',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='palabra',
            name='lastUpdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
