# Generated by Django 4.0.2 on 2022-02-06 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Palabras', '0005_alter_palabra_datedeleted_alter_palabra_lastupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palabra',
            name='dateDeleted',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='palabra',
            name='lastUpdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
