# Generated by Django 4.0.2 on 2022-02-06 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Palabras', '0006_alter_palabra_datedeleted_alter_palabra_lastupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palabra',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Deleted', 'Deleted')], default='Active', max_length=7),
        ),
    ]
