# Generated by Django 4.0.2 on 2022-02-06 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Palabras', '0007_alter_palabra_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Palabra',
            new_name='Palabras',
        ),
    ]
