# Generated by Django 4.0.2 on 2022-02-06 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Palabras', '0008_rename_palabra_palabras'),
    ]

    operations = [
        migrations.RenameField(
            model_name='palabras',
            old_name='_id',
            new_name='id',
        ),
    ]
