# Generated by Django 4.0.2 on 2022-02-06 03:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Palabras', '0009_rename__id_palabras_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palabras',
            name='dateCreated',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='palabras',
            name='lastUpdate',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
