# Generated by Django 4.0.2 on 2022-02-06 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Palabras', '0011_alter_palabras_datecreated_alter_palabras_lastupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palabras',
            name='dateDeleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
